title: GDG Bologna
description: Il sito ufficiale di GDG Bologna, dove scriveremo a proposito dei nostri eventi.

url: http://gdgbologna.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: gdgbologna
   twitter: gdgbologna
   facebook: gdgbologna
   email: info@gdgbologna.com

google_analytics: "UA-74403554-1"
