# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GDG Bologna
email: info@gdgbologna.org
description: > # this means to ignore newlines until "baseurl:"
  Google Developers Group di Bologna.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gdgbologna.com" # the base hostname & protocol for your site
twitter_username: gdgbologna
github_username:  gdgbologna

# Build settings
markdown: kramdown
